# Site settings
title: Sheldon Chen 的自言自语
email: sheldonziping@163.com
description: Even the smallest person can change the course of the future
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sheldontalk.com" # the base hostname & protocol for your site
twitter_username: SheldonChen1
github_username: sheldonzipingchen

# Build settings
markdown: kramdown
